name: CI
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install CMake
      run: sudo apt-get install -y cmake
    - name: Build formatter_lib
      run: cd formatter_lib && mkdir -p build && cd build && cmake .. && cmake --build . && cd ../..
    - name: Build formatter_ex_lib
      run: cd formatter_ex_lib && mkdir -p build && cd build && cmake .. && cmake --build . && cd ../..
    - name: Build hello_world
      run: cd hello_world && mkdir -p build && cd build && cmake .. && cmake --build . && cd ../..
    - name: Build solver
      run: cd solver && mkdir -p build && cd build && cmake .. && cmake --build . && cd ../..

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build formatter_lib
      run: |
        cd formatter_lib
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
        cd ../..
    - name: Build formatter_ex_lib
      run: |
        cd formatter_ex_lib
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
        cd ../..
    - name: Build hello_world
      run: |
        cd hello_world
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
        cd ../..
    - name: Build solver
      run: |
        cd solver
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Release
        cd ../..
